name: Camera Mouse Packaging
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
jobs:
  python:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt
