name: Camera Mouse Packaging
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  python:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src/pyTracker
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Package
        run: pyinstaller --onefile --windowed src/main.py
      - name: Check dist folder content
        run: dir
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Camera Mouse Python Package
          path: src/pyTracker/dist/main/main.exe.notanexecutable
  electronWindows:
    runs-on: windows-latest
    needs: python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Download python build artifact
        uses: actions/download-artifact@v2
        with:
          name: Camera Mouse Python Package
          path: src/pyTracker/dist
      - name: Package
        run: npm run make
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Camera Mouse Package Exe
          path: out/make
