name: Camera Mouse Packaging
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  electron:
    runs-on: ubuntu-latest
    needs: python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Check directory content
        run: ls -l .
      - name: Package
        run: npm run make
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Camera Mouse Package
          path: dist
