name: Camera Mouse Packaging
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # python:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: src/pyTracker
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.8
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: Package
  #       run: pyinstaller --onefile --windowed src/main.py
  #     - name: Upload
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Camera Mouse Python Package
  #         path: src/pyTracker/dist
  electron:
    runs-on: ubuntu-latest
    # needs: python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Check directory content
        run: ls -l .
      - name: Package
        run: npm run make
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Camera Mouse Package
          path: dist
